print:
  instances: 1
  streams:
    defaultStream:
      fields: []
      targets: {}
split:
  instances: 1
  streams:
    default:
      fields: [word]
      targets:
        count:
          type: fields
          targetFields: [word]
count:
  instances: 1
  streams:
    default:
      fields: [word, count]
      targets:
        print: {type: shuffle}
